export const ADD_TASK = "ADD_TASK";
export const REMOVE_TASK = "REMOVE_TASK";
export const ADD_CATEGORY = "ADD_CATEGORY";
export const REMOVE_CATEGORY = "REMOVE_CATEGORY";
export const ADD_CATEGORY_TASK = "ADD_CATEGORY_TASK";
export const REMOVE_CATEGORY_TASK = "REMOVE_CATEGORY_TASK";
