export const ADD_TASK = "ADD_TASK";
export const REMOVE_TASK = "REMOVE_TASK";
export const EDIT_TASK = "EDIT_TASK";

export const ADD_DONE_TASK = "ADD_DONE_TASK";
export const REMOVE_DONE_TASK = "REMOVE_DONE_TASK";

export const ADD_CATEGORY = "ADD_CATEGORY";
export const REMOVE_CATEGORY = "REMOVE_CATEGORY";
export const EDIT_CATEGORY = "EDIT_CATEGORY";

export const ADD_CATEGORY_TASK = "ADD_CATEGORY_TASK";
export const REMOVE_CATEGORY_TASK = "REMOVE_CATEGORY_TASK";
export const EDIT_CATEGORY_TASK = "EDIT_CATEGORY_TASK";

export const ADD_DONE_CATEGORY_TASK = "ADD_DONE_CATEGORY_TASK";
export const REMOVE_DONE_CATEGORY_TASK = "REMOVE_DONE_CATEGORY_TASK";

export const UPDATE_DETAILS = "UPDATE_DETAILS";
